hostname: '127.0.0.1'
port: 8100
docker-compose-file: ./docker-compose.yml
projects:
  service: ../service
  push-service: ../service
  test-service: ../service
  frontend: ../frontend
  backend: ../backend
script: ./update.sh
interval: 60s
